/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DTO.NomeIDDTO;
import DTO.OngDTO;
import VIEW.Trabalhoo;
import javax.swing.*;
import javax.swing.text.MaskFormatter;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;

/**
 *
 * @author joaop
 */
public class Trabalho extends javax.swing.JFrame {

    /**
     * Creates new form Trabalho
     */
    public Trabalho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Id1 = new javax.swing.JLabel();
        Telefone1 = new javax.swing.JLabel();
        Cnpj1 = new javax.swing.JLabel();
        Descricao1 = new javax.swing.JLabel();
        Id2 = new javax.swing.JLabel();
        Telefone2 = new javax.swing.JLabel();
        Cnpj2 = new javax.swing.JLabel();
        Descricao2 = new javax.swing.JLabel();
        Id3 = new javax.swing.JLabel();
        Telefone3 = new javax.swing.JLabel();
        Cnpj3 = new javax.swing.JLabel();
        Descricao3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Nome1 = new javax.swing.JLabel();
        Doacao1 = new javax.swing.JLabel();
        Endereco1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        Nome2 = new javax.swing.JLabel();
        Doacao2 = new javax.swing.JLabel();
        Endereco2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        Nome3 = new javax.swing.JLabel();
        Doacao3 = new javax.swing.JLabel();
        Endereco3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NomeLogado = new javax.swing.JLabel();
        IDLogado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        pagina = new javax.swing.JLabel();

        Id1.setText("jLabel1");

        Telefone1.setText("jLabel2");

        Cnpj1.setText("jLabel3");

        Descricao1.setText("jLabel3");

        Id2.setText("jLabel1");

        Telefone2.setText("jLabel2");

        Cnpj2.setText("jLabel3");

        Descricao2.setText("jLabel3");

        Id3.setText("jLabel1");

        Telefone3.setText("jLabel2");

        Cnpj3.setText("jLabel3");

        Descricao3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 700));

        jPanel3.setBackground(new java.awt.Color(229, 229, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(470, 602));

        Nome1.setBackground(new java.awt.Color(0, 0, 0));
        Nome1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Nome1.setForeground(new java.awt.Color(0, 0, 0));
        Nome1.setText("Nome Ong ");

        Doacao1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Doacao1.setForeground(new java.awt.Color(102, 204, 0));
        Doacao1.setText("Doação");

        Endereco1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Endereco1.setForeground(new java.awt.Color(0, 0, 0));
        Endereco1.setText("Endereço");

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(167, 21, 21));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Recarregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Nome2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Nome2.setForeground(new java.awt.Color(0, 0, 0));
        Nome2.setText("Nome Ong");

        Doacao2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Doacao2.setForeground(new java.awt.Color(102, 204, 0));
        Doacao2.setText("Doação");

        Endereco2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Endereco2.setForeground(new java.awt.Color(0, 0, 0));
        Endereco2.setText("Endereço");

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Nome3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Nome3.setForeground(new java.awt.Color(0, 0, 0));
        Nome3.setText("Nome Ong");

        Doacao3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Doacao3.setForeground(new java.awt.Color(102, 204, 0));
        Doacao3.setText("Doação");

        Endereco3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Endereco3.setForeground(new java.awt.Color(0, 0, 0));
        Endereco3.setText("Endereço");

        jButton3.setBackground(new java.awt.Color(51, 153, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/31282031_5irt_tsz4_220824-removebg-preview.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        NomeLogado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NomeLogado.setForeground(new java.awt.Color(51, 51, 255));
        NomeLogado.setText("jLabel2");

        IDLogado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IDLogado.setForeground(new java.awt.Color(51, 51, 255));
        IDLogado.setText("jLabel3");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Seja Bem-Vindo(a)! - ");

        jButton5.setBackground(new java.awt.Color(51, 153, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Próxima Página");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(51, 153, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Página Anterior");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        pagina.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pagina.setForeground(new java.awt.Color(0, 0, 0));
        pagina.setText("1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Nome2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Endereco2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Doacao2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(49, 49, 49))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Doacao3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(48, 48, 48))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Nome3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Endereco3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(77, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomeLogado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IDLogado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Nome1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Endereco1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Doacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(pagina)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(102, 102, 102))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(NomeLogado)
                    .addComponent(IDLogado))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nome1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Endereco1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Doacao1))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Endereco2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Doacao2)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Endereco3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Doacao3)
                    .addComponent(jButton3))
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(pagina)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Trabalhoo desc = new Trabalhoo();
        OngDTO ong = new OngDTO();
        ong.setId(Id1.getText());
        ong.setNome(Nome1.getText());
        ong.setTelefone(Telefone1.getText());
        ong.setEndereco(Endereco1.getText());
        ong.setCnpj(Cnpj1.getText());
        ong.setDoacao(Doacao1.getText());
        ong.setDescricao(Descricao1.getText());
        NomeIDDTO idn = new NomeIDDTO();
        idn.setNomeLogado(NomeLogado.getText());
        idn.setIdLogado(IDLogado.getText());
        desc.importarLoggin(idn);
        desc.importarInfos(ong);
        desc.setVisible(true);
        desc.setTitle("Descrição - " + Nome1.getText());
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Trabalhoo desc = new Trabalhoo();
        OngDTO ong = new OngDTO();
        ong.setId(Id2.getText());
        ong.setNome(Nome2.getText());
        ong.setTelefone(Telefone2.getText());
        ong.setEndereco(Endereco2.getText());
        ong.setCnpj(Cnpj2.getText());
        ong.setDoacao(Doacao2.getText());
        ong.setDescricao(Descricao2.getText());
        NomeIDDTO idn = new NomeIDDTO();
        idn.setNomeLogado(NomeLogado.getText());
        idn.setIdLogado(IDLogado.getText());
        desc.importarLoggin(idn);
        desc.importarInfos(ong);
        desc.setVisible(true);
        desc.setTitle("Descrição - " + Nome2.getText());
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Trabalhoo desc = new Trabalhoo();
        OngDTO ong = new OngDTO();
        ong.setId(Id3.getText());
        ong.setNome(Nome3.getText());
        ong.setTelefone(Telefone3.getText());
        ong.setEndereco(Endereco3.getText());
        ong.setCnpj(Cnpj3.getText());
        ong.setDoacao(Doacao3.getText());
        ong.setDescricao(Descricao3.getText());
        NomeIDDTO idn = new NomeIDDTO();
        idn.setNomeLogado(NomeLogado.getText());
        idn.setIdLogado(IDLogado.getText());
        desc.importarLoggin(idn);
        desc.importarInfos(ong);
        desc.setVisible(true);
        desc.setTitle("Descrição - " + Nome3.getText());
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Recarga();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Prox();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Ant();
    }//GEN-LAST:event_jButton6ActionPerformed

    public void Recarga() {
        pagina.setText("0");
        String id[] = new String[3];
        String nome[] = new String[3];
        String telefone[] = new String[3];
        String endereco[] = new String[3];
        String cnpj[] = new String[3];
        String doacao[] = new String[3];
        String descricao[] = new String[3];
        String url = "jdbc:mysql://localhost:3306/a3psc?user=root&password=testea3psc123!";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            for (int limite = 0; limite < 3; limite++) {
                String sql = "SELECT * FROM ong LIMIT 1 OFFSET ?;";
                try (Connection conn = DriverManager.getConnection(url); PreparedStatement stmt = conn.prepareStatement(sql)) {
                    stmt.setInt(1, limite);
                    try (ResultSet rsid = stmt.executeQuery()) {
                        if (rsid.next()) {
                            id[limite] = rsid.getString("id");
                            nome[limite] = rsid.getString("nome");
                            doacao[limite] = rsid.getString("doacao");
                            endereco[limite] = rsid.getString("endereço");
                            telefone[limite] = rsid.getString("telefone");
                            cnpj[limite] = rsid.getString("cnpj");
                            descricao[limite] = rsid.getString("descricao");

                        }
                    } catch (SQLException e) {
                        e.printStackTrace();
                    }

                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            Nome1.setText(nome[0]);
            Doacao1.setText(doacao[0]);
            Endereco1.setText(endereco[0]);
            Id1.setText(id[0]);
            Telefone1.setText(telefone[0]);
            Descricao1.setText(descricao[0]);
            Cnpj1.setText(cnpj[0]);
            Nome2.setText(nome[1]);
            Doacao2.setText(doacao[1]);
            Endereco2.setText(endereco[1]);
            Id2.setText(id[1]);
            Telefone2.setText(telefone[1]);
            Descricao2.setText(descricao[1]);
            Cnpj2.setText(cnpj[1]);
            Nome3.setText(nome[2]);
            Doacao3.setText(doacao[2]);
            Endereco3.setText(endereco[2]);
            Id3.setText(id[2]);
            Telefone3.setText(telefone[2]);
            Descricao3.setText(descricao[2]);
            Cnpj3.setText(cnpj[2]);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void Prox() {
        String limiteString = pagina.getText();
        int limite = Integer.parseInt(limiteString);
        limite += 3;
        int set = 0;
        String id[] = new String[3];
        String nome[] = new String[3];
        String telefone[] = new String[3];
        String endereco[] = new String[3];
        String cnpj[] = new String[3];
        String doacao[] = new String[3];
        String descricao[] = new String[3];
        String url = "jdbc:mysql://localhost:3306/a3psc?user=root&password=testea3psc123!";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            for (int i = limite; i < (limite + 3); i++) {
                String sql = "SELECT * FROM ong LIMIT 1 OFFSET ?;";
                try (Connection conn = DriverManager.getConnection(url); PreparedStatement stmt = conn.prepareStatement(sql)) {
                    stmt.setInt(1, i);
                    try (ResultSet rsid = stmt.executeQuery()) {
                        if (rsid.next()) {
                            id[set] = rsid.getString("id");
                            nome[set] = rsid.getString("nome");
                            doacao[set] = rsid.getString("doacao");
                            endereco[set] = rsid.getString("endereço");
                            telefone[set] = rsid.getString("telefone");
                            cnpj[set] = rsid.getString("cnpj");
                            descricao[set] = rsid.getString("descricao");
                            set++;

                        }
                    } catch (SQLException e) {
                        e.printStackTrace();
                    }

                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            Nome1.setText(nome[0]);
            Doacao1.setText(doacao[0]);
            Endereco1.setText(endereco[0]);
            Id1.setText(id[0]);
            Telefone1.setText(telefone[0]);
            Descricao1.setText(descricao[0]);
            Cnpj1.setText(cnpj[0]);
            Nome2.setText(nome[1]);
            Doacao2.setText(doacao[1]);
            Endereco2.setText(endereco[1]);
            Id2.setText(id[1]);
            Telefone2.setText(telefone[1]);
            Descricao2.setText(descricao[1]);
            Cnpj2.setText(cnpj[1]);
            Nome3.setText(nome[2]);
            Doacao3.setText(doacao[2]);
            Endereco3.setText(endereco[2]);
            Id3.setText(id[2]);
            Telefone3.setText(telefone[2]);
            Descricao3.setText(descricao[2]);
            Cnpj3.setText(cnpj[2]);
            pagina.setText(String.valueOf(limite));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void Ant() {
        String limiteString = pagina.getText();
        int limite = Integer.parseInt(limiteString);
        if (limite == 0) {

        } else {
            limite -= 3;
            int set = 0;
            String id[] = new String[3];
            String nome[] = new String[3];
            String telefone[] = new String[3];
            String endereco[] = new String[3];
            String cnpj[] = new String[3];
            String doacao[] = new String[3];
            String descricao[] = new String[3];
            String url = "jdbc:mysql://localhost:3306/a3psc?user=root&password=testea3psc123!";

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                for (int i = limite; i < (limite + 3); i++) {
                    String sql = "SELECT * FROM ong LIMIT 1 OFFSET ?;";
                    try (Connection conn = DriverManager.getConnection(url); PreparedStatement stmt = conn.prepareStatement(sql)) {
                        stmt.setInt(1, i);
                        try (ResultSet rsid = stmt.executeQuery()) {
                            if (rsid.next()) {
                                id[set] = rsid.getString("id");
                                nome[set] = rsid.getString("nome");
                                doacao[set] = rsid.getString("doacao");
                                endereco[set] = rsid.getString("endereço");
                                telefone[set] = rsid.getString("telefone");
                                cnpj[set] = rsid.getString("cnpj");
                                descricao[set] = rsid.getString("descricao");
                                set++;

                            }
                        } catch (SQLException e) {
                            e.printStackTrace();
                        }

                    } catch (SQLException e) {
                        e.printStackTrace();
                    }
                }
                Nome1.setText(nome[0]);
                Doacao1.setText(doacao[0]);
                Endereco1.setText(endereco[0]);
                Id1.setText(id[0]);
                Telefone1.setText(telefone[0]);
                Descricao1.setText(descricao[0]);
                Cnpj1.setText(cnpj[0]);
                Nome2.setText(nome[1]);
                Doacao2.setText(doacao[1]);
                Endereco2.setText(endereco[1]);
                Id2.setText(id[1]);
                Telefone2.setText(telefone[1]);
                Descricao2.setText(descricao[1]);
                Cnpj2.setText(cnpj[1]);
                Nome3.setText(nome[2]);
                Doacao3.setText(doacao[2]);
                Endereco3.setText(endereco[2]);
                Id3.setText(id[2]);
                Telefone3.setText(telefone[2]);
                Descricao3.setText(descricao[2]);
                Cnpj3.setText(cnpj[2]);
                pagina.setText(String.valueOf(limite));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public void importarLoggin(NomeIDDTO idn) {

        IDLogado.setText(idn.getIdLogado());
        NomeLogado.setText(idn.getNomeLogado());

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trabalho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cnpj1;
    private javax.swing.JLabel Cnpj2;
    private javax.swing.JLabel Cnpj3;
    private javax.swing.JLabel Descricao1;
    private javax.swing.JLabel Descricao2;
    private javax.swing.JLabel Descricao3;
    private javax.swing.JLabel Doacao1;
    private javax.swing.JLabel Doacao2;
    private javax.swing.JLabel Doacao3;
    private javax.swing.JLabel Endereco1;
    private javax.swing.JLabel Endereco2;
    private javax.swing.JLabel Endereco3;
    private javax.swing.JLabel IDLogado;
    private javax.swing.JLabel Id1;
    private javax.swing.JLabel Id2;
    private javax.swing.JLabel Id3;
    private javax.swing.JLabel Nome1;
    private javax.swing.JLabel Nome2;
    private javax.swing.JLabel Nome3;
    private javax.swing.JLabel NomeLogado;
    private javax.swing.JLabel Telefone1;
    private javax.swing.JLabel Telefone2;
    private javax.swing.JLabel Telefone3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel pagina;
    // End of variables declaration//GEN-END:variables
}
